default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: polyclinic
  password: polyclinic
  host: localhost
  port: 5432

development:
  <<: *default
  database:  Polyclinic_development

test:
  <<: *default
  database: Polyclinic_test

production:
  <<: *default
  database: Polyclinic_production
  username: Polyclinic
  password: <%= ENV['POLYCLINIC_DATABASE_PASSWORD'] %>
